language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.3
    - env: DBTYPE=sqlite; MW=master
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: never
    on_failure: always
